sim: Fail on Error/Fatal message in output log (#48)
VCS does not seem to exit with an error code when either of these happen,
so emulate it by looking for the "Error: " or "Fatal: " prefixes at the
start of the line produced by $error/$fatal.

diff --git a/scripts/start_vcs b/scripts/start_vcs
--- a/scripts/start_vcs
+++ b/scripts/start_vcs
@@ -3,4 +3,11 @@
 # Solderpad Hardware License, Version 0.51, see LICENSE for details.
 # SPDX-License-Identifier: SHL-0.51
 
+set -eo pipefail
+
 bin/axi_llc.vcs +vcs+lic+wait +ntb_random_seed=1 | tee logs/axi_llc.vcs.log
+
+if grep -E '^(Error|Fatal):' logs/axi_llc.vcs.log -A 1; then
+    echo >&2 "Testbench failed"
+    exit 1
+fi
